spring:
  application:
    name: upload-onedrive
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

azure:
  tenant-id: ${AZURE_TENANT_ID}
  client-id: ${AZURE_CLIENT_ID}
  client-secret: ${AZURE_CLIENT_SECRET}

logging:
  level:
    root: DEBUG